---
title: "CFU plot"
author: "Yassine El Chazli"
date: "25/01/2022"
output:
  md_document:
    variant: markdown_github
  html_document: default
  pdf_document: default
---


```{r, setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


#### These are the required package to reproduce this analysis.

```{r, echo = T, eval=T, message=F, warning=F, results=F}

### env setup

required_packages = c("dplyr", "data.table", "ggplot2", "ggbeeswarm", "ggpubr", "EnvStats", "tidyverse",  "ggforce", "wesanderson", "RcolorBrewer", "ggthemes" , "scales")
need_install = required_packages[!(required_packages) %in% installed.packages()]

if (length(need_install) > 0){
  install.packages((need_install),repos = "http://cran.us.r-project.org")
}

# Load packages
lapply(required_packages, require, character.only=T)

dir_script = dirname(rstudioapi::getSourceEditorContext()$path)

setwd(dir_script)
#font_import()
#loadfonts(device="win")

```

#### Load the data 
```{r, echo = T, eval=T, message=F, warning=F, results=F}

cfu_count <- fread("CFU_count.csv") %>%
  drop_na() %>%
  group_by(Time) %>%
  mutate(Time_d = Time / 24,
    cfumax = max(CFU), 
         cfumin = min(CFU),
    Colonized = case_when(CFU > 50 ~1,
                          TRUE ~ 0))
cfu_summary <- cfu_count %>%
  filter(Gut == "Ileum") %>%
  group_by(Time) %>% 
  summarise(avg = mean(CFU), stdev = sd(CFU), Colonization = sum(Colonized)/n()*100)

setDT(cfu_count)
```

##### Figure 3B
```{r, eval=T, echo=T, message=FALSE, warning=FALSE, results=F}

ggplot(cfu_count, aes(x = Time, y = CFU))+
  stat_summary(data=cfu_count[Gut=="Ileum"],fun=mean, geom="line", color = "salmon", stroke =0)  +
  stat_summary(data=cfu_count[Gut=="Ileum"],fun.data=mean_sdl, fun.args = list(mult=1), 
               geom="point", shape=17, size=2, color="salmon", stroke =0) +
  geom_point(data=cfu_count[Condition=="Inoculum"], 
             fill="#6388b4", color = "black", height = 0, width = 1, shape=22, size = 1.5, stroke=0.25)+
  geom_quasirandom(data=cfu_count[Gut=="Ileum"], fill="grey70",
                   color = "black", height = 0, width = 1, shape=21, size = 1.5, stroke=0.25) +
  geom_hline(yintercept=50, col="black", linetype = "dashed") +
  theme(text=element_text(size=7),
        panel.background = element_rect(fill = "white", colour = "grey50"),
        panel.border = element_rect(colour = "grey", fill=NA, size=1),
        axis.text.x = element_text(color = "black", size=7), 
        axis.text.y = element_text(color = "black", size=7),
        axis.title.x =element_text(color = "black", size=7), 
        axis.title.y =element_text(color = "black", size=7),
         aspect.ratio=1)+
    scale_y_log10( name = "CFU's / Ileum", breaks = scales::trans_breaks("log10", function(x) 10^x),
                 labels = scales::trans_format("log10", scales::math_format(10^.x))) +
  annotation_logticks(sides = "l") +
  scale_x_continuous(limits = c(0,80), breaks = seq(0, 80, by = 8))+
  xlab("Time (h)")+
  annotate("text", x=40, y=14, size=1.75, label= "Colonization Success (%)")+
  geom_text(data=cfu_summary, aes(label=paste0(round(Colonization,0),"%"),y=6), size=1.75)
 ggsave("Fig3b_revised.pdf",device=cairo_pdf, width=90, height= 60, units = "mm", dpi = 600)
```
