---
title: "CFU_plot"
output:
  html_document:
    df_print: paged
  pdf_document: default
---

```{r, echo=FALSE}
knitr::opts_chunk$set(error = TRUE)
knitr::opts_chunk$set(fig.width=120, fig.height=80) 
```

```{r, echo = F}
library(knitr)
opts_chunk$set(tidy.opts=list(width.cutoff=80),tidy=TRUE)
```

```{r wrap-hook, eval=T}
library(knitr)
hook_output = knit_hooks$get('output')
knit_hooks$set(output = function(x, options) {
  # this hook is used only when the linewidth option is not NULL
  if (!is.null(n <- options$linewidth)) {
    x = knitr:::split_lines(x)
    # any lines wider than n should be wrapped
    if (any(nchar(x) > n)) x = strwrap(x, width = n)
    x = paste(x, collapse = '\n')
  }
  hook_output(x, options)
})
```

#### These are the required package to reproduce this analysis.

```{r, echo = T, eval=T, message=F, warning=F, results=F}

### env setup

required_packages = c("dplyr", "data.table", "ggplot2", "readxl", "ggbeeswarm", "ggpubr", "EnvStats", "tidyverse", "patchwork", "ggforce", "wesanderson", "RcolorBrewer", "extrafont", "ggthemes" ,"egg", "scales", "ggh4x","grid")
need_install = required_packages[!(required_packages) %in% installed.packages()]

if (length(need_install) > 0){
  install.packages((need_install))
}

# Load packages
lapply(required_packages, require, character.only=T)

dir_script = dirname(rstudioapi::getSourceEditorContext()$path)

setwd(dir_script)
#font_import()
#loadfonts(device="win")

```

#### Load the data 
```{r, echo = T, eval=T, message=F, warning=F, results=F}

cfu_count <- read_csv("CFU_count.csv") %>%
  drop_na() %>%
  group_by(Time) %>%
  mutate(Time_d = Time / 24,
    cfumax = max(CFU), 
         cfumin = min(CFU),
    Colonized = case_when(CFU > 50 ~1,
                          TRUE ~ 0))
cfu_summary <- cfu_count %>%
  group_by(Time) %>% 
  filter(Gut == "Ileum") %>%
  summarise(avg = mean(CFU), stdev = sd(CFU), Colonization = sum(Colonized)/n()*100)
 
### Panel 3C data
metab_enrich <- read_csv("../Metabolite_enrichments.csv") %>%
  group_by(Time, Class) 

cfu_summary <- cfu_count %>%
  group_by(Time) %>% 
  filter(Gut == "Ileum") %>%
  summarise(avg = mean(CFU), stdev = sd(CFU), Colonization = sum(Colonized)/n()*100)

inoculum= cfu_count[cfu_count$Time!= 0, ]

cfu_count$switch_time = cfu_count$Time-24
cfu_summary$switch_time = cfu_summary$Time-24
```

##### Figure 3B
```{r, echo = T, eval=T, message=F, warning=F, results=F}

ggplot(subset(cfu_count, Gut %in% c("Ileum")), aes(x = switch_time, y = CFU))+
  stat_summary(fun=mean, geom="line", aes(group=Gut), color = "gray", alpha=0.5, stroke =0)  +
  stat_summary(fun.data=mean_sdl, fun.args = list(mult=1), 
               geom="pointrange", color="gray", alpha=0.5 , stroke =0) +
  geom_beeswarm(data= subset(cfu_count, switch_time==-24), size=1.2, colour= "blue", alpha = 0.5, width =1, stroke =0 )+
  geom_quasirandom(fill = "goldenrod2", height = 0, width = 0.5, size = 1.2, colour = "black", alpha=0.5, stroke =0) +
  geom_hline(yintercept=50, col="black", linetype = "dashed") +
  theme(text=element_text(size=8,  family="Arial"),
        panel.background = element_rect(fill = "white", colour = "grey50"),
        panel.border = element_rect(colour = "grey", fill=NA, size=1),
        axis.text.x = element_text(color = "black", size=8), axis.text.y = element_text(color = "black", size=8),
        axis.title.x =element_text(color = "black", size=8), axis.title.y =element_text(color = "black", size=8),
        plot.margin = unit(c(0.2,0.2,0.2,0.2), "cm"))+
  scale_y_log10(name = "CFUs / Ileum",
        breaks = trans_breaks("log10", function(x) 10^x),
        labels = trans_format("log10", math_format(10^.x)))+
  scale_x_continuous(name = "Time (h)", limits=c(-24, 48), breaks=seq(-24, 48, 8)) +
  annotate("text", x=15, y=14, size=2, label= "Colonization Success (%)")+
  geom_text(data=cfu_summary, aes(label=paste0(round(Colonization,0),"%"),y=6), size=2)+
  force_panelsizes(rows = unit(1.6, "in"), cols = unit(2.4, "in"))

ggsave("CFU_plot_Sn_Figure4.pdf" ,device=cairo_pdf, width=3, height= 2, units = "in", dpi = 300) 

````

